public function a => print("hello")
function b: String => return d("world")
function c(some value: String) => print(value)
function d(_ value: String): String => return g(some: value)

public function e {
    print("hello")
}

function f: String {
    return "world"
}

function g(some value: String): String {
    return value
}

function main {
    a() // "hello"
    c("world")
    assert(b() equals "world")
}